# A estrutura correta do render.yaml

databases:
  - name: db-receitas         # Um nome para o nosso recurso de banco de dados
    databaseName: recipe_book_db  # O nome da base de dados interna a ser criada
    user: app_user          # O nome do utilizador a ser criado
    plan: free              # O plano gratuito

services:
  - type: web
    name: api-livro-de-receitas
    plan: free
    env: docker
    database: db-receitas
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1