version: "1"

services:
  - type: psql
    name: db-receitas
    plan: free

  - type: web
    name: api-livro-de-receitas
    plan: free
    env: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-receitas
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: 1